name: Rspec

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev mysql-server
        sudo apt-get update -qq
        curl -L https://packagecloud.io/michaelmior/coinor/gpgkey | sudo apt-key add -
        echo "deb https://packagecloud.io/michaelmior/coinor/ubuntu/ precise main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get install -qq coinor-libcbc-dev coinor-libcbc3 coinor-libcoinutils-dev coinor-libcoinutils3v5 coinor-libosi-dev coinor-libosi1v5 coinor-libclp-dev coinor-libclp1 coinor-libcgl-dev coinor-libcgl1 libstdc++6
        sudo apt install libpq-dev
        gem install bundler
        mysql -uroot -e 'create database nose;'
        mysql -uroot -Dnose < spec/support/data/mysql.sql
        sudo rm -rf /var/lib/cassandra/*
        wget https://archive.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz && tar -xvzf apache-cassandra-3.7-bin.tar.gz && sudo sh apache-cassandra-3.7/bin/cassandra -R && sleep 15
        bundle install --jobs 4 --retry 3
        sed -i '/^--tag/d' .rspec
        sed -ie 's/GurobiModel/CbcModel/g' ./lib/nose/search/problem.rb
        
    - name: Run Test
      run: |
        bundle exec rspec
